config/routes.rb
Rails.application.routes.draw do
  resources :gift_lists do 
  	resources :items
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift_list.rb
class GiftList < ApplicationRecord
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :gift_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gift_lists_controller.rb
class GiftListsController < ApplicationController
  before_action :set_gift_list, only: [:show, :edit, :update, :destroy]

  # GET /gift_lists
  # GET /gift_lists.json
  def index
    @gift_lists = GiftList.all
  end

  # GET /gift_lists/1
  # GET /gift_lists/1.json
  def show
  end

  # GET /gift_lists/new
  def new
    @gift_list = GiftList.new
  end

  # GET /gift_lists/1/edit
  def edit
  end

  # POST /gift_lists
  # POST /gift_lists.json
  def create
    @gift_list = GiftList.new(gift_list_params)

    respond_to do |format|
      if @gift_list.save
        format.html { redirect_to @gift_list, notice: 'Gift list was successfully created.' }
        format.json { render :show, status: :created, location: @gift_list }
      else
        format.html { render :new }
        format.json { render json: @gift_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gift_lists/1
  # PATCH/PUT /gift_lists/1.json
  def update
    respond_to do |format|
      if @gift_list.update(gift_list_params)
        format.html { redirect_to @gift_list, notice: 'Gift list was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift_list }
      else
        format.html { render :edit }
        format.json { render json: @gift_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gift_lists/1
  # DELETE /gift_lists/1.json
  def destroy
    @gift_list.destroy
    respond_to do |format|
      format.html { redirect_to gift_lists_url, notice: 'Gift list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift_list
      @gift_list = GiftList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_list_params
      params.fetch(:gift_list, {}).permit(:title, :event_date, :description)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    gift_list_id = params[:gift_list_id]
    @gift_list = GiftList.find(gift_list_id)
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :gift_list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gift_lists_helper.rb
module GiftListsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/gift_lists/_form.html.erb
<%= form_with(model: gift_list, local: true) do |form| %>
  <div>
    <label>Title</label>
    <%= form.text_field :title %>
  </div>
  <div>
    <label>Event Date</label>
    <%= form.date_field :event_date %>
  </div>
  <div>
    <label>Description</label>
    <%= form.text_field :description %>
  </div>
  <% if gift_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gift_list.errors.count, "error") %> prohibited this gift_list from being saved:</h2>

      <ul>
      <% gift_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gift_lists/edit.html.erb
<h1>Editing Gift List</h1>

<%= render 'form', gift_list: @gift_list %>

<%= link_to 'Show', @gift_list %> |
<%= link_to 'Back', gift_lists_path %>

app/views/gift_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gift Lists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th>Title</th>
      <th>Event Date</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% @gift_lists.each do |gift_list| %>
      <tr>
        <td><%= gift_list.title %></td>
        <td><%= gift_list.event_date %></td>
        <td><%= gift_list.description %></td>
        <td><%= link_to 'Show', gift_list %></td>
        <td><%= link_to 'Edit', edit_gift_list_path(gift_list) %></td>
        <td><%= link_to 'Destroy', gift_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift List', new_gift_list_path %>
<%= javascript_pack_tag 'hello_react' %>

app/views/gift_lists/new.html.erb
<h1>New Gift List</h1>

<%= render 'form', gift_list: @gift_list %>

<%= link_to 'Back', gift_lists_path %>

app/views/gift_lists/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @gift_list.title %></h2>
<p><%= @gift_list.event_date.strftime("%B #{@gift_list.event_date.day.ordinalize}") %></p>
<p><%= @gift_list.items.count %> gifts</p>
<p><%= @gift_list.description %></p>
<ul>
	<% @gift_list.items.each do |item| %>
	<li><h3><%= item.title %></h3></li>
	<% end %>
</ul>
<%= link_to 'Edit', edit_gift_list_path(@gift_list) %> |
<%= link_to 'Back', gift_lists_path %>
<%= link_to 'Add Item', new_gift_list_item_path(@gift_list) %>

app/views/items/_form.html.erb
<%= form_for([gift_list, item], local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Gift list</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.gift_list %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item, gift_list: @gift_list %>

<%= link_to 'Back', gift_list_items_path(@gift_list) %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Gift list:</strong>
  <%= @item.gift_list.title %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiftApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>